### ISSUE TITLE
Add clubhouse.io integration

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-plugins#105]
https://clubhouse.io

**Comment by cannikin** [comment]
I'm surprised you guys haven't got more requests for this one, Clubhouse is the new hotness in project management! Starting to see stores of people leaving Jira to come over here.

Is plugin development open source in any way? Can I patch something together and open a pull request?

**Comment by benvinegar** [comment]
So, obviously this whole repository is open source, and there are instructions for checking out the main Sentry project, checking out sentry-plugins, and developing a new plugin. Many of our plugins today were developed this way.

The problem is that if we officially endorse such a plugin (and make it available via sentry.io), we're now responsible for it, and it's not typical that the original contributors stick around to make sure bug fixes and updates are made for other users. If the plugin breaks (e.g. because Clubhouse changes their API) – it's now on us, and if we don't deliver users become upset.

**Comment by devteamexpress** [comment]
+1

**Comment by BenCoffeed** [comment]
+1

**Comment by cannikin** [comment]
I'd happy write it myself but I'm not a Python guy. :( Anyone else?

**Comment by BenCoffeed** [comment]
I've opened a support request with ClubHouse and they mentioned that they use Sentry internally and there is interest in a Sentry plugin there as well. So, 🤞 we'll see something from the Clubhouse side.

**Comment by aledoo** [comment]
+1000

**Comment by flxfxp** [comment]
+10000

**Comment by ste00martin** [comment]
I want this

**Comment by mmartinson** [comment]
How does sentry.io make business decisions about which plugins to officially support? I would make the case that clubhouse could be a high value integration to bring/keep paying customers.

I asked Clubhouse about it and their CS lead told me "I've been in touch with the team at Sentry and their product and engineering team would appreciate comments on this Issue <linked to this issue>"

**Comment by esauro** [comment]
This would be a fantastic thing to have. Absolutely desirable. Please bring clubhouse support to sentry.io ;)

**Comment by bendavies** [comment]
Echoing the above. Would love to see clubhouse integration.

**Comment by jamtur01** [comment]
Ditto - would like to see this.

**Comment by miketheman** [comment]
Would the sentry.io team accept a PR for this and work it's way into the release cycle?

**Comment by mattrobenolt** [comment]
At this point, most likely yes. We just currently don’t have capacity to do this ourselves, and we’re more willing to just accept the risk. Especially with this many interested parties, if it becomes broken, I think one of the 40 people who have given a thumbs up to the issue would jump in and help.

**Comment by samphilipd** [comment]
We'd use it.

**Comment by miketheman** [comment]
I'm going to take a crack at this. @mattrobenolt is there any particular guidance you might be able to offer that I might stumble across, and would save me time upfront? 😀

**Comment by jamtur01** [comment]
@miketheman Happy to review although my Python is mighty rusty. :)

**Comment by miketheman** [comment]
PR #324 created. @mattrobenolt @jamtur01 Let me know what you think.

**Comment by drkolos** [comment]
We would definitely use it. Happy to support the development of it.
