### ISSUE TITLE
[slack] Handle proxy

### ISSUE THREAD

**Issue by badr-badri** [getsentry/sentry-plugins#115]
Hello, 

I'm facing this issue today: 
the sentry server can reach internet only by using a proxy. How do I configure slack plugin to use this proxy so it can be able to send notifications ?

Thanks,

**Comment by mattrobenolt** [comment]
This is untested on our side, but in theory, setting `HTTP_PROXY` and `HTTPS_PROXY` environment variables would solve the issue since we ultimately use the `requests` library. See: http://docs.python-requests.org/en/master/user/advanced/#proxies
