### ISSUE TITLE
Can't set Icon URL = "" in Slack plugin settings

### ISSUE THREAD

**Issue by sfermigier** [getsentry/sentry-plugins#121]
Here's the error message:
<img width="583" alt="screen shot 2017-01-10 at 14 48 39" src="https://cloud.githubusercontent.com/assets/271079/21808585/32878986-d744-11e6-8e37-bdbe4f2bdc23.png">

or:

```
Icon URL
The url of the icon to appear beside your bot (32px png), leave empty for none.
You may use http://myovchev.github.io/sentry-slack/images/logo32.png
Not a valid URL.
```

**Comment by rbroen** [comment]
I can confirm that leaving it empty is invalid. Besides that, the 32x32px png I linked to... did not work either.

**Comment by dansgithubuser** [comment]
I have a URL set. No error message, but when I test the plugin the slack message has no icon.

**Comment by meloman-a** [comment]
> I have a URL set. No error message, but when I test the plugin the slack message has no icon.

I also have the same issue. Anyone has worked this out?

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
