### ISSUE TITLE
GitLab plugin - 404 when testing with repository name

### ISSUE THREAD

**Issue by uda** [getsentry/sentry-plugins#122]
Following issue #34, which regarded the GitLab internal issue with a dot in the path.
As I wrote there, in my case, the issue is the `/` in the namespace, according to the docs, you should use `%2F` as `NAMESPACE` and `PROJECT_NAME` separator.

It appears we don't escape the slash, but we do escape the percent, so when I tried setting `%2F` I got `%25%2F` on gitlab's end, and again received a 404.

See: https://gitlab.com/help/api/projects.md#get-single-project

**Comment by lippoliv** [comment]
👍

**Comment by LordMike** [comment]
A workaround is to use the project Id. It has the side effect that any links to the Gitlab issue will use the project ID instead of the repo name, which is an invalid link..

But at least issue creation/updating works.

**Comment by morph027** [comment]
Thanks for the workaround @LordMike

**Comment by krisztiankocsis** [comment]
The workaround is only a half solution because now Sentry provides the GL-XXX link to Gitlab with project ID which is non-existent from Gitlab side (404).

**Comment by uda** [comment]
I just now fixed the issue for us, Sentry does escape the slashes to `%2F`, but some proxies or LBs on the way have decoded the URI, in our case, nginx.

So, for me this issue is solved:
- Apache - set `AllowEncodedSlashes NoDecode` on the relevant host or location
- nginx - make sure to use `proxy_pass` WITHOUT a trailing slash, simply 'http://127.0.0.1:8080` or something like that
