### ISSUE TITLE
[JIRA] On-Prem Sentry with jira_ac plugin

### ISSUE THREAD

**Issue by Awk34** [getsentry/sentry-plugins#123]
When I try to configure the Sentry plugin for JIRA, it lists me my Sentry.io org only. It appears that there's no way to set it up with my on-prem Sentry install. Is this possible?

**Comment by Awk34** [comment]
I See "From the manage add-on page in JIRA, choose 'Upload add-on' and copy the URL for the descriptor view." at the bottom of the README, and I have my sentry exposed at https://sentry.mysite.com/, but I have no idea what it means by "URL for the descriptor view"

**Comment by Awk34** [comment]
Digging into the Python (which I don't know Python..), I was able to deduce that the AC descriptor is served from https://sentry.mysite.com/plugins/jira-ac/atlassian-connect.json. This should be updated in the docs.

**Comment by nhumrich** [comment]
I tried to use that url (replacing the host with my own of course) as the upload url and got a "we couldn't install this add-on". Am I missing  any other steps you might have done?

**Comment by Awk34** [comment]
@nhumrich make sure you install/enable the JIRA AC plugin on your Sentry server

**Comment by nhumrich** [comment]
I guess im lost. I have the pip package installed, and the json page loads:

```
{
  "scopes": [
    "read"
  ],
  "authentication": {
    "type": "jwt"
  },
  "vendor": {
    "url": "https://sentry.io",
    "name": "Sentry"
  },
  "name": "Sentry for JIRA",
  "key": "sentry.mysite.com.jira_ac",
  "lifecycle": {
    "installed": "/plugins/jira-ac/installed"
  },
  "modules": {
    "configurePage": {
      "url": "/plugins/jira-ac/config",
      "name": {
        "value": "Configure Sentry Add-on"
      },
      "key": "configure-sentry"
    },
    "webPanels": [
      {
        "url": "/plugins/jira-ac/plugin?issueKey={issue.key}",
        "location": "atl.jira.view.issue.right.context",
        "key": "sentry-issues",
        "name": {
          "value": "Related Sentry Issues"
        }
      }
    ]
  },
  "baseUrl": "https://sentry.mysite.com",
  "apiVersion": 1,
  "description": "Sentry add-on for JIRA"
}
```

is there a place in the ui where I actually need to enable it? im not finding one.

**Comment by TMaCEvans** [comment]
I'm experiencing exactly the same problem as
@nhumrich 
I'm using Cloud hosted Jira rather than Jira Server could this impact the install of this plugin?

**Comment by nhumrich** [comment]
@TMaCEvans I solved this somehow.. I think all I had to do was go into a specific project and enable the jira integration. You have to set it up per project.

**Comment by KyeRussell** [comment]
Is anyone able to provide any more info on getting this to work? I'm using self-hosted Sentry + JIRA Cloud. I don't think I'm given an opportunity to upload my own plugin as it stated above.

**Comment by DevJackSmith** [comment]
I installed the Sentry on premise v9.1.1. The legacy plugin works just fine, but we want the new features from the jira_ac new integration. So I was able to go to Jira and install from the json url provided above. I was also able to verify that jira_ac is turned on in Sentry by going to https://sentry.mysite.com/settings/cloudbeds/projects/myproject/plugins/jira-ac/ it shows enabled there but no other info/options. But unfortunately, that's not enough.

Any ideas on how to make the new Jira integration work on latest Sentry on premise? (any help appreciated)

**Comment by andrepcg** [comment]
@DevJackSmith Same here. I could successfully upload an app from that url but it shows Jira as not installed and there's no way to configure it

**Comment by neotreat** [comment]
Having the same issue: The JIRA-Plugin was installed successfully on my JIRA cloud instance (via the URL to jira_ac). It correctly allowed to select an organisation, but now I'm stuck. In my Sentry on-premise instance the JIRA plugin is still marked as disabled and I have no possibility to configure the JIRA sync. Any help would be appreciated!

**Comment by markstory** [comment]
The integration listed in the organization integrations list *is not* the jira_ac project plugin. We're hoping to have documentation published for getting the organization integration setup soon.

**Comment by neotreat** [comment]
Okay, that explains my confusion. Thanks for the feedback, then I'll wait for the documentation update.

**Comment by sgabler** [comment]
I'm currently trying to integrate the JIRA plugin with our self-hosted Sentry. Did your team happen to have time to update the documentation already? I searched, but couldn't find it. Maybe I missed something? @markstory

**Comment by markstory** [comment]
Yes documentation was posted [in the forums](https://forum.sentry.io/t/how-to-configure-jira-cloud-in-your-on-premise-sentry/6720).

**Comment by Awk34** [comment]
@markstory can this be closed then?
