### ISSUE TITLE
sentry errors aren't triggering slack notifications

### ISSUE THREAD

**Issue by rlam3** [getsentry/sentry-plugins#126]
i’m trying to integrate sentry into slack. 

i have added my webhook but when i try triggering errors, i only get emails and nothing is coming in on my slack channel. 

i created the integration/configuration through slacks app directory.

is anybody else having a similar issue?

**Comment by paulius005** [comment]
Experiencing the same issue here. Is there anything on my end that I can do to help debug this issue?

**Comment by mattrobenolt** [comment]
My only guess is it'd be related to your project's notification rules. The Slack plugin definitely is working as intended, it's just a matter of figuring out why it's not working as you expect.

**Comment by confiks** [comment]
We suddenly stopped receiving Slack notifications as well from February 3 on, without having changed any of the notification settings.
