### ISSUE TITLE
Plugins not showing up in sentry integrations after install

### ISSUE THREAD

**Issue by roh85** [getsentry/sentry-plugins#134]
I am trying to integrate sentry on premises with our JIRA cloud instance. I have installed the sentry plugins and ran the database migrations with the sentry upgrade command but the plugins are not showing up in sentry.

I have executed the following commands
- source /www/sentry/bin/activate
- pip install sentry-plugins 
- SENTRY_CONF=/etc/sentry sentry upgrade

I have rebooted the OS to make sure that the plugins are reloaded. Am I missing something?

**Comment by carlitux** [comment]
I am having same issue

**Comment by carlitux** [comment]
There is a table where plugins's metadata is stored?

**Comment by carlitux** [comment]
After with a few time and reading some code... the issue is in settings if we have to change any feature we have to rewrite all features using this as base: https://github.com/getsentry/sentry/blob/4c8269275824f8d947f17a32bee31c2635ee18b6/src/sentry/conf/server.py#L737 in file `sentry.conf.py`

**Comment by woqer** [comment]
I solved this by reloading the sentry services. They should add that to the README

**Comment by shadow1349** [comment]
I'm having the same issue, restarting the sentry services didn't work for me.

**Comment by carlitux** [comment]
@shadow1349 review your settings, if you are set the `SENTRY_FEATURES ` variable maybe you disabled the other ones.

**Comment by shadow1349** [comment]
@carlitux I checked the sentry.config.py and I didn't have SENTRY_FEATURES I also cheacked the config.yaml and nothing as well

**Comment by carlitux** [comment]
Take a look that sentry and plugins are installed in same workspace, I did that mistake before.

**Comment by shadow1349** [comment]
@carlitux ah I see. I installed both sentry and sentry-plugins using pip so shouldn't that, by default, install them in the same place?

**Comment by shadow1349** [comment]
@carlitux got it. That was, in fact the issue.

Thanks for your help!

**Comment by thetemplar** [comment]
Hey,
I am trying to get the plugins running myself, but they are not showing up.
I did
```
pip install sentry-plugins
sentry upgrade
reboot
```
but it does not work. Any ideas?

**Comment by carlitux** [comment]
@thetemplar did you read the thread? most of the issues are the settings.

**Comment by thetemplar** [comment]
I read it, but I am not sure if I got it all.

I checked my config for:
 SENTRY_FEATURES = {
 'projects:plugins': True
... 

Did I miss something?

**Comment by carlitux** [comment]
Run these commands:

```bash
source /home/sentry/sentry_app/bin/activate  # activate the environment
pip install sentry-plugins
```

After that restart all your services with supervisor

**Comment by neo-yuanyanjun** [comment]
I have the same issue when i install this plugin [https://github.com/anshengme/sentry-dingding](https://github.com/anshengme/sentry-dingding)
