### ISSUE TITLE
Feature request: default component for JIRA

### ISSUE THREAD

**Issue by shosti** [getsentry/sentry-plugins#137]
With the JIRA integration, you can currently set default project, priority, and issue type, which is awesome. It would also be great to be able to set a default component, since Sentry projects often map nicely to JIRA components. (This would also allow you to implicitly set a default assignee for issues.)

I'd be happy to work on a PR for this if it makes sense.

**Comment by benjaminWFoxIntel** [comment]
i would love to see this integration working

**Comment by arunkumargit** [comment]
Is this feature request in development pipeline?

**Comment by ratio91** [comment]
+1, would be really useful!  any update here?
