### ISSUE TITLE
Slack/mattermost - dynamic destination (channel/user) based on tag or condition

### ISSUE THREAD

**Issue by Wilkolicious** [getsentry/sentry-plugins#138]
I was wondering if sentry could send alerts to different slack channels and/or users based upon a tag.  So, like the email alert title can use `${tag:environment}`, can the value of a tag key=>value pair be used to direct these alerts to a particular destination.

Or perhaps there could be a different way of changing slack destinations based upon if they are generated from a development environment or production environment?  Otherwise, everything gets dumped into one channel.

Thank you in advance!

**Comment by sambauers** [comment]
I have a similar need. Which is to filter out certain environments from sending to Slack.

**Comment by EvanPurkhiser** [comment]
[The new slack integration supports this!](https://blog.sentry.io/2018/04/02/sentry-plus-slack)
