### ISSUE TITLE
Jira: Unauthorized: either your username and password were invalid or you do not have access

### ISSUE THREAD

**Issue by andrewbaxter** [getsentry/sentry-plugins#142]
We have two projects with the same Jira machine account.  It was working, then suddenly creating issues stopped working, and re-entering credentials gave this message.  I double checked everything.  I logged in via a browser several times (prompted for captcha) then tried the integration again and it worked.

Is it possible it's hitting a captcha?  If that's the case, it would be very useful to have that information in the error message.

**Comment by CaliLuke** [comment]
I'm having issues logging in too. Considering how crucial JIRA is to the workflow of so many companies I'm annoyed with the little attention this integration seems to receive, it's been quite a while.

**Comment by donnoman** [comment]
Atlassian forced a change to group-based syncing, which I believe affects the password:
```
Atlassian just wanted to remind you that the switch to group-based syncing changes are coming soon. If you haven't already, you'll need to disconnect and reconnect your G Suite integration by April 28, 2017 to avoid any problems. We've added the details from the last email here just in case you need a refresher on what's happening.```

Now we get the above as well. It doesn't matter which admin account is used, it always says invalid.

**Comment by respondcreate** [comment]
I'm also experiencing this issue.

**Comment by reidab** [comment]
We're hitting this as well, after the recent forced switch from Jira accounts to Atlassian accounts for sign-in.

**Comment by andrewbaxter** [comment]
Related https://github.com/getsentry/sentry-plugins/issues/190 https://github.com/getsentry/sentry-plugins/issues/182
Summarizing from the second one, it seems that Atlassian Connect was the intended upgrade path but api issues mean that doesn't have ticket creation functionality currently.

**Comment by rom-melnik** [comment]
I have the same problem. Can you fix this?
Thanks

**Comment by adsahay** [comment]
Same issue here. Any known workarounds?

**Comment by bpiselli** [comment]
Same issue : Hmmm what to do, what to do ?

**Comment by adsahay** [comment]
Update: I disabled my Jira plugin and re-enabled it, and it worked. I'm not using Google Auth, just email + password.

**Comment by lisaross** [comment]
Disabling and re-enabling (on both sides) didn't work for me. Anyone else have any suggestions?

**Comment by sheluchin** [comment]
Disabling and re-enabling doesn't work here.

**Comment by sreeram-boyapati** [comment]
Facing this issue. We do not know how to use our cloud jira instance with sentry.
