### ISSUE TITLE
How to get slack integration going?

### ISSUE THREAD

**Issue by sirvon** [getsentry/sentry-plugins#149]
How do I start getting this integration going?

With almost every major Mobile/DevOps tool, integration with slack is almost seemless.

Crashlytics has slack integration, where you just enter in credentials in dashboard

Slack is pretty integral for all dev teams these days...
And so is Sentry!

Why isn't this easier to do when using sentry?

Thanks for the lib!

**Comment by mattrobenolt** [comment]
To be clear, this is source code for running and deploying your own Sentry server. If you're just a sentry.io customer, you don't need to reference this at all, and you can just enable the plugin on your project settings.
