### ISSUE TITLE
Slack notifications never send.

### ISSUE THREAD

**Issue by octoxan** [getsentry/sentry-plugins#154]
Using the sentry.io, with the Slack integration enabled, no notifications are received in Slack.

**Comment by thecantero** [comment]
I also have the same problem. On additional note, I don't see a "Test configuration" button on my Slack integration config.

**Comment by chytreg** [comment]
@dcramer or @macqueen Could someone take a look what is going on?

**Comment by chytreg** [comment]
@octoxan, @thecantero after these changes it starts to work for me:
![image](https://cloud.githubusercontent.com/assets/142751/25004583/5afbe92a-2055-11e7-9626-f2b38d09f123.png)

and in Slack settings

![image](https://cloud.githubusercontent.com/assets/142751/25004595/6d56833c-2055-11e7-8cbc-d2bb3e7fd126.png)

**Comment by emaniacs** [comment]
@chytreg i try that configuration, but still got no notification from sentry.io, and even i add another rules.

![screen shot 2017-05-31 at 4 22 20 pm](https://cloud.githubusercontent.com/assets/314789/26625142/69cf4ada-461d-11e7-8ffd-f4465262b501.png)


![screen shot 2017-05-31 at 4 22 29 pm](https://cloud.githubusercontent.com/assets/314789/26625175/7d25ae4e-461d-11e7-8214-3de016f5d9b9.png)

**Comment by chytreg** [comment]
@emaniacs  What can I say - magic, works for me :(, If I were you I would write to sentry support.

**Comment by emaniacs** [comment]
ok @chytreg thanks for the tips, i gonna try it :)

**Comment by jyclam** [comment]
@emaniacs Have you gotten slack integration to work yet? I finally got mine to work following the instructions above (to set a rule) and also installing sentry-plugins in my worker. If you're using [sentry/onpremise](https://github.com/getsentry/onpremise), you'll have to do the following: 

`docker-compose exec worker bash`
`pip install sentry-plugins`
`sentry upgrade`
`exit`
`docker-compose restart worker`

**Comment by emaniacs** [comment]
The integration now work, i dont know what happen but iam happy :)

**Comment by ArcticSnowman** [comment]
Legacy Slack seems to have been removed from 9.1.1.

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
