### ISSUE TITLE
Update GitLab plugin to use API v4 rather than v3

### ISSUE THREAD

**Issue by connorshea** [getsentry/sentry-plugins#158]
We deprecated API v3 in GitLab 9.0 last month. v4 is now the currently supported version, though v3 will stick around for a while.

https://docs.gitlab.com/ee/api/v3_to_v4.html

**Comment by rvanlaak** [comment]
@connorshea would be great if you could add the date when v3 will get removed, so the Sentry team can prioritize this.

**Comment by uda** [comment]
@rvanlaak it was already removed, from version 9.5.

Though some instances might have the old versions, Sentry should not need to support them since it is easy to upgrade and those versions are practically a security hole.

**Comment by connorshea** [comment]
@uda that's untrue, v3 is still in the current master of GitLab. API v3 and v4 are available simultaneously from 9.0 to the current release (10.3), it'll be available until at least 11.0 I believe.

**Comment by uda** [comment]
Sorry @connorshea, I stand corrected, the v3 endpoints are still available.

But since the old versions w/o v4 are not advised, and the change for this plugin is not major beyond base-url change, there is no reason to hold back.

**Comment by laubstein** [comment]
As from Gitlab 11, api v3 is removed:

https://about.gitlab.com/2018/06/22/gitlab-11-0-released/#gitlab-api-v3

**Comment by laubstein** [comment]
Fixed since 9.0.0rc1 (fce97ac3a3375cecf287916f0c8d1acda4d0aec3)
