### ISSUE TITLE
is Integration with self-hosted on-premise JIRA instance possible?

### ISSUE THREAD

**Issue by vladgurovich** [getsentry/sentry-plugins#163]
The current docs refer to Atlassian-hosted JIRA marketplace. 
How can i set up the integration with self-hosted instance instead?

**Comment by voylinux** [comment]
I am also interested about that point.

**Comment by kluvi** [comment]
It works... there is field to input JIRA URL. Tested yesterday.

**Comment by vladgurovich** [comment]
@kluvi Sentry docs point to installing a Sentry plugin in your Jira instance. However that installation only allows installing a plugin on Atlassian-hosted cloud version of JIRA, not on self-hosted version of JIRA.

Can you describe your setup and how you got the integration to work?

**Comment by kluvi** [comment]
@vladgurovich I have not tried the "Sentry for JIRA"  plugin. I installed  https://github.com/getsentry/sentry-plugins into Sentry. This allows us to create JIRA issues directly from Sentry.

**Comment by ChillarAnand** [comment]
@vladgurovich Did you manage to get it work?

@kluvi How did you install it? [Docs says](https://github.com/getsentry/sentry-plugins#jira-atlassian-connect-ui-plugin) to install jira plugin?

**Comment by stayallive** [comment]
Curious about this too. The marketplace extension does not allow (as far as I can see) to set another Sentry URL.

Is it possible to use the (new, non-legacy) JIRA integration on a on-premise Sentry?

(this is the marketplace plugin I am looking at: https://marketplace.atlassian.com/apps/1219432/sentry-for-jira?hosting=cloud&tab=overview)

**Comment by markstory** [comment]
To use the integration in self-hosted you'll need to create your own atlassian connect application. To do that you'll need:

1. An [atlassian developer account](https://developer.atlassian.com/cloud/jira/platform/getting-started/).
2. Enable development mode in your Jira instance under `Gear Icon > Manage Apps > Settings`
3. Create a new connect application using the descriptor JSON found at  `https://<your-instance>/extensions/jira/descriptor/`

**Comment by stayallive** [comment]
^ A+, thanks @markstory!

**Comment by wryun** [comment]
https://forum.sentry.io/t/how-to-configure-jira-cloud-in-your-on-premise-sentry/6720

worked perfectly for us.
