### ISSUE TITLE
Unable to create JIRA issue with custom field of type 'Date Time Picker'

### ISSUE THREAD

**Issue by mcheshier1** [getsentry/sentry-plugins#185]
Hi Sentry team, I'm trying to create issues in JIRA and one of the custom fields I have is for a timestamp of when the alert was received. The error I'm getting is:

Error Communicating with Jira (HTTP 400): customfield_11100: Operation value must be a string

I know this particular field is the Date Time Picker field because I added an exclusion for customfield_11100 and it disappeared. Since this is a required field, though, I can't create an issue without it.

Things I've tried:

5/19/2017
Unix timestamp like 1495214522
2017-05-19T17:22:02+00:00 (ISO)
05/19/2017 @ 5:22pm (UTC)
Friday, 19-May-17 17:22:02 UTC (RFC 2822)
2017-05-19T17:22:02+00:00 (RFC 3339)

Since none of these work, I'm guessing this is some sort of data parsing issue when you're sending to JIRA itself.

**Comment by houdaiye** [comment]
hi,hao to fix?
