### ISSUE TITLE
Unable to integrate with JIRA

### ISSUE THREAD

**Issue by rhapsodixx** [getsentry/sentry-plugins#190]
It seems the integration to JIRA haven't been working for a while. Tried to create JIRA manually from issue detail page but it show "Unauthorized", tried to reset configuration but it keeps saying my authorization invalid or no access which is weird because its working until a week ago.

**Comment by keimlink** [comment]
We're having the same issues. Maybe the reason is Atlassian's switch to id.atlassian.com?

**Comment by jkelley79** [comment]
Same here.

**Comment by keimlink** [comment]
I deleted the configuration and created a new one a week ago. Works now. 🎉

**Comment by mkhattab** [comment]
I'm also having the same issue when trying to setup the JIRA plugin.

**Comment by rom-melnik** [comment]
I have the same problem. Can you fix this?
Thanks

**Comment by bpiselli** [comment]
Same : please can you solve it ?

**Comment by vivekagarwal1984** [comment]
Do we have a fix or a workaround for it?

**Comment by pmmaga** [comment]
[This](https://github.com/getsentry/sentry-plugins/issues/182#issuecomment-371390071) did the trick for me.
