### ISSUE TITLE
Log 'sentry-slack' error

### ISSUE THREAD

**Issue by gellerb** [getsentry/sentry-plugins#195]
`RuntimeError: Found 'sentry-slack'. This has been superseded by 'sentry-plugins', so please uninstall.`

The above line and a Traceback error regarding 'sentry-slack' are in my Sentry Logs. I'm using Sentry 8.17.0 with the **native** Slack integration. It's unclear why I'm seeing this error.

Full Log:
[sentry-d2x7v.sentry.log.txt](https://github.com/getsentry/sentry-plugins/files/1093277/sentry-d2x7v.sentry.log.txt)

**Comment by mattrobenolt** [comment]
The error means exactly what it says. You have the old versions of the plugins installed and the new versions. You need to uninstall the old versions.
