### ISSUE TITLE
Feature Request: Bitbucket Server Plugin

### ISSUE THREAD

**Issue by MrMorice** [getsentry/sentry-plugins#197]
It would be great if we can connect our on-premise Sentry to our on-premise Bitbucket Server repository for commit data. Thanks for your support and the great product! All the best, Moritz

**Comment by grossadamm** [comment]
Looks like there would need to be work done to the core sentry app to support authenticating against an on-premise Bitbucket Server. https://github.com/getsentry/sentry/blob/master/src/social_auth/backends/bitbucket.py

**Comment by JuniorSilva5150** [comment]
Yes, please.

**Comment by levisbakalinsky** [comment]
Bump. Any plans on anyone picking this up?

**Comment by dKemen** [comment]
We'd really appreciate this too

**Comment by thetemplar** [comment]
Is there a possibility by now to link a Bitbucket Server to sentry?

**Comment by toabi** [comment]
Not in 9.0.0

**Comment by ArcticSnowman** [comment]
Seeing as I've not been able to set LDAP working, this would be great..

**Comment by pszalko** [comment]
@toabi Any estimate about Jira Server integration?

**Comment by toabi** [comment]
@pszalko I'm not a sentry/plugin dev, I just upgraded to 9.0.0 and found out that Bitbucket Server is not possible (yet).

**Comment by AdamLeyshon** [comment]
+1 for this please. On-premise Sentry and Jira/Bitbucket setup.

**Comment by juruus** [comment]
Yes please...

**Comment by kuczek** [comment]
+1

**Comment by realdadfish** [comment]
Would you people please use GitHub's 👍 functionality under the original comment and / or alternatively subscribe silently to this thread? Thanks!

**Comment by emanuelezambrano** [comment]
+1

**Comment by HlebKrah** [comment]
+1

**Comment by pleugenio** [comment]
+1

**Comment by asapzacy** [comment]
+100

**Comment by JiRadu** [comment]
+1

**Comment by BYK** [comment]
This repo is deprecated. You may follow the progress of this issue over at getsentry/sentry#8372
