### ISSUE TITLE
GitLab: Hint at possibility to enter project ID

### ISSUE THREAD

**Issue by janw** [getsentry/sentry-plugins#207]
With our particular GitLab deployment config, I am continuously experiencing 404 project not found errors when setting up Sentry/GitLab integration for a project. As per the [API docs](https://docs.gitlab.com/ce/api/projects.html#get-single-project), there's always the possibility to query for a project ID instead of it's URL-encoded path. 

It would be nice to add to the help text of the `Repository Name` field in the GitLab plugin that entering a project ID is possible as well. Something like

```
Enter your repository name, including the owner, or the project ID
```

**Comment by uda** [comment]
@janwh, regarding the 404 issue, check if my latest comment on #122 helps.
