### ISSUE TITLE
Feature request: Sending notifications to multiple slack channels

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-plugins#224]
This is something we'd love to be able to do. I don't know if it's generic enough so that it can be common to "all" notification system (which have the concept of a channel).

**Comment by EvanPurkhiser** [comment]
[The new slack integration supports this!](https://blog.sentry.io/2018/04/02/sentry-plus-slack)

**Comment by bsergean** [comment]
Excellent !
We are using the on-premise version of sentry, I can't wait to get that last version installed.
