### ISSUE TITLE
[JIRA] Trying to link sentry issue to Jira issue

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-plugins#227]
### Steps to reproduce:

1. Open Sentry issue
2. Select `Link to existing Jira issue`
3. Try to search Jira issue by ID like `AB1234-123`

### Expected result:

Issue will be displayed in link

### Actual result:

Message with `no results were found`.

But if you try to search by Jira issue name - you will get expected issue in result list.

#### Versions:

* JIRA v7.4.2
* Sentry 8.19.0

**Comment by nicktong** [comment]
Hi, is there any update on this bug?

**Comment by apastuhow** [comment]
It seems no

**Comment by jcasner** [comment]
Duplicate of #111?

**Comment by lzzparis** [comment]
We're having the same problem which makes the integration only partially useful.  We have no problem creating a new Jira ticket from Sentry, but it's almost impossible to link existing Jira issues (other than the ones suggested before you type anything, perhaps the 5 most recently created?)
