### ISSUE TITLE
can't assignee issue to gitlab user

### ISSUE THREAD

**Issue by nunesvictor** [getsentry/sentry-plugins#229]
Even after configure integration to Gitlab I can't assignee the issue to any Gitlab user, that because the assignee select is always empty.

Sorry for the poor english.

**Comment by uda** [comment]
The issue is with GitLab, when requesting members of a project from the API you'll get only direct members w/o group members.

See: https://gitlab.com/gitlab-org/gitlab-ce/issues/40202

**Comment by nunesvictor** [comment]
I think we can close that for now than
