### ISSUE TITLE
Jira plugin: default issue type setting has no choices

### ISSUE THREAD

**Issue by dmnd** [getsentry/sentry-plugins#234]
I have the Jira plugin set up for my project at https://sentry.io/flexport/flexport/settings/plugins/jira/

I created a new Jira issue type called "Sentry". I want to set this as the default in the plugin settings, but something seems to be broken on Sentry's side:

![image](https://user-images.githubusercontent.com/4427/30455791-0d5b7e18-9956-11e7-9e15-9929bbd7df41.png)

The option doesn't list anything. I have about ten issue types in my Jira project, though:

![image](https://user-images.githubusercontent.com/4427/30455780-00ef659a-9956-11e7-8993-50ec77761c42.png)

**Comment by brianmartin** [comment]
We're seeing this dropdown empty as well. Not sure if relevant, but we don't have any custom types (just out-of-the-box JIRA cloud).

**Comment by jstewart37** [comment]
Hi, were you able to resolve this? I am seeing the same issue

**Comment by brianmartin** [comment]
Hey @jstewart37, I can't really say as I've switched jobs.
