### ISSUE TITLE
Error in slack plugin: Cannot resolve keyword 'project' into field

### ISSUE THREAD

**Issue by cmmata** [getsentry/sentry-plugins#235]
Hello,

I have been using Sentry and the Slack plugin for about a year, and today I realized that it has stopped working. When I go to a project configuration and send a test plugin from Slack integration, I see this message:
```
Test Results:
"There was an internal error with the Plugin"
```
Then I see a new bug in that project with the sentry-slack error:
```
FieldError
Cannot resolve keyword 'project' into field. Choices are: id, key, label, project_id, status, values_seen
sentry_plugins/slack/plugin.py in _get_tags at line 108
        key_labels = {
            o.key: o.get_label()
            for o in TagKey.objects.filter(
                project=event.project,
                key__in=[t[0] for t in tag_list], <--- this one is 108
            )
        }
        value_labels = {
            (o.key, o.value): o.get_label()
            for o in TagValue.objects.filter(
```
Maybe it comes from the last Sentry update, I think I updated it last Tuesday. I saw a database error because of insufficient permissions. I solved the error, launched update again and didn't see any other update error.

What can be wrong?

**Comment by mattrobenolt** [comment]
My only guess is that the version of sentry-plugins is not matching the version of sentry. They must always be the same.

So if sentry server is 8.20.0, you need 8.20.0 of plugins as well.

**Comment by cmmata** [comment]
Okay, looks like a rookie error.. Sorry about that! Honestly I thought that `sentry-plugins` were been updating in each Sentry upgrade process. I have updated it and now it's working again. Thank you!
