### ISSUE TITLE
JIRA integration not working

### ISSUE THREAD

**Issue by 2ps** [getsentry/sentry-plugins#239]
Our jira integration shows as not working and the list of projects is not being pulled into from JIRA for us to create linked tickets.

**Comment by mattmso** [comment]
Having the same issue 
Jira version: v7.3.1
Sentry: 8.21.0.dev0

**Comment by asiebert** [comment]
To be precise, are you also getting the following error when trying to create a JIRA from Sentry?
```
Error in JIRA configuration, no projects found for user [USERNAME].
```

**Comment by jokerejoker** [comment]
I cannot authenticate. Existing projects that used to be working, works no more. Have checked the JIRA end.

**Comment by asiebert** [comment]
cc. @dcramer , your latest changes on the JIRA plugin (90b2918595b98aebe24aff6ef05bd830a8c434fc and #237) occurred just a few hours before the first report here and within our team.
Don't see anything obviously wrong in those changes, but ain't familiar with this codebase.

**Comment by mattmso** [comment]
@asiebert yes I see 'Error in JIRA configuration, no projects found for user [USERNAME].' when trying to create a jira ticketf rom sentry

**Comment by hanswesterbeek** [comment]
Same here.
