### ISSUE TITLE
Sentry Slack Integration Not Working (version 8.17.0)

### ISSUE THREAD

**Issue by degupta** [getsentry/sentry-plugins#240]
When I try to configure my Slack Integration Its show up like this:

<img width="1061" alt="screen shot 2017-09-18 at 9 03 50 pm" src="https://user-images.githubusercontent.com/4096104/30550407-00bd223a-9cb5-11e7-8743-a9c1a0a320c5.png">

It should show up like this (according to Slack):

![sentry_step4](https://user-images.githubusercontent.com/4096104/30550440-14d0ae7c-9cb5-11e7-9c04-565c6f13f35c.png)

**Comment by degupta** [comment]
Is there any update on this?

**Comment by mattrobenolt** [comment]
You need to make sure the version installed of sentry-plugins matches the version of sentry. If they are matching, there won’t be any issues.
