### ISSUE TITLE
Discord Plugin

### ISSUE THREAD

**Issue by CGreenburg** [getsentry/sentry-plugins#249]
This would be very similar to Slack's plugin, only for [Discord](https://discordapp.com/).

**Comment by drptbl** [comment]
You can use `Slack` plugin for that, just add `/slack` at the end of `Discord` webhook url and use it with `Slack` integration (put `Discord` webhook url in field called `Webhook URL*`. It will work just fine.

**Comment by CGreenburg** [comment]
Wow I didn't even think of that. I ended up creating a lambda function that forwarded on the data to discord. :sweat_smile:

**Comment by kaitoAckerman** [comment]
@drptbl ? I cant find any setting to insert Webhook url while configuring slack intergration. Is that obsolete? 

need help please!

**Comment by kaitoAckerman** [comment]
whoopss! .. nvm. I got that after checking out #10889.

**Comment by framerate** [comment]
I think Slack integration has changed, it's asking me to add a workspace. I don't have a slack workspace, I just want to access the webhook for Discord. Am I missing anything?

**Comment by galpratama** [comment]
> I think Slack integration has changed, it's asking me to add a workspace. I don't have a slack workspace, I just want to access the webhook for Discord. Am I missing anything?

yes, just search on the search box for "Slack (Legacy)" like this one
https://github.com/getsentry/sentry/pull/10889
