### ISSUE TITLE
VictorOps Plugin Improvements

### ISSUE THREAD

**Issue by wagner-victorops** [getsentry/sentry-plugins#252]
Hey guys.  It would be great if the payload to VictorOps also included the project number and issue number from Sentry.

For example (plugin.py)

```
response = client.trigger_incident(
            message_type=message_type,
            entity_id=group.id,
            entity_display_name=event.title,
            state_message=self.build_description(event),
            timestamp=int(event.datetime.strftime('%s')),
            project_number=<project # here>
            issue_number=<issue # here>
        )
```

You have already covered the basic required fields for VictorOps, which means that you can now add any additional fields that you feel would be relevant or useful information for Sentry users to know when they get notified of an issue.

We are more than happy to partner with you guys to iterate on this and test.  (I work for VictorOps).  Thanks!

**Comment by ajeeshgit** [comment]
This would be really helpful for the  customers who  uses  third party tools to monitor the applications / infrastructure  and victor ops to integrate alerts  .Project number and issue number in the sentry  payload helps the user to retrieve  details of incident  from sentry . Could you prioritize this one?

**Comment by MaxBittker** [comment]
hi @wagner-victorops we're probably not prioritizing this in our coming sprints, but if this is a simple self contained change, we'd be happy to be proactive about reviewing and helping merge a small PR.

**Comment by wagner-victorops** [comment]
@MaxBittker Thanks for the heads up.  You can find the PR here: https://github.com/getsentry/sentry-plugins/pull/276

Thanks.

**Comment by MaxBittker** [comment]
@wagner-victorops thanks for the PR, but it looks like it doesn't work. Would you mind taking a look at the test result? seems to be using undefined variables

**Comment by mikel-arena** [comment]
I created a new PR with the relevant information added: #431

**Comment by mikel-arena** [comment]
SInce it appears @wagner-victorops PR went stale, I created a new PR with the relevant information added: #431

@MaxBittker

**Comment by MaxBittker** [comment]
nice job, the PR looks good! (thanks for updating the test case)

somebody else is gonna have to approve it to get it merged though, don't have access
