### ISSUE TITLE
AttributeError: 'SlackPlugin' object has no attribute 'add_notification_referrer_param'

### ISSUE THREAD

**Issue by bond-os** [getsentry/sentry-plugins#253]
Hello,
 with sentry 8.20, slack plugin is not working:
>pip list installed | grep sentry
>sentry (8.20.0)
>sentry-plugins (8.20.0)

> 10:31:18 [INFO] sentry.events: post_process.skip.raw_event (event_id=102600L)
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/project_plugin_details.py", line 55, in post
    test_results = plugin.test_configuration(project)
  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 160, in test_configuration

>  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry_plugins/slack/plugin.py", line 238, in notify
    'title_link': self.add_notification_referrer_param(group.get_absolute_url()),
AttributeError: 'SlackPlugin' object has no attribute 'add_notification_referrer_param'
10:31:18 [ERROR] root: Plugin(slack) raised an error during test

some guides for fixing it?

**Comment by mattrobenolt** [comment]
Are you super sure they’re both 8.20 and everything has been restarted? That method it’s complaining about seems like the server version is not 8.20 since it was added for that release. It sounds like the plugins are newer than the server.
