### ISSUE TITLE
JIRA plugin returning ill-formatted values for autocomplete user field

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry-plugins#265]
JIRA user field isn't displaying search results correctly for autocomplete dropdown. (Starting happening roughly 2 weeks ago). Assignee dropdown works correctly. 

cc @getsentry/workflow

**Comment by dcramer** [comment]
Do we know what exactly autocomplete dropdowns we're seeing this in? Or the type of those? Having trouble reproducing.

**Comment by MeredithAnya** [comment]
I believe it is just a user picker field
