### ISSUE TITLE
Unable to create JIRA tickets from Sentry

### ISSUE THREAD

**Issue by elianatixtrack** [getsentry/sentry-plugins#268]
We use JIRA Cloud. When I try to create a JIRA ticket from within Sentry (or link to an existing one), I get the following error: 

> "JIRA returned: Unauthorized. Please check your username, password, instance and project in your configuration settings."

If I go to Sentry's Project Settings > All Integrations > JIRA (v8.22.0.dev0) and enter my current login (I am a JIRA admin), it fails with a similar error:

> "Unauthorized: either your username and password were invalid or you do not have access"

I've tried using the JIRA username and password as well as email and password. I even tried changing the JIRA URL to id.atlassian.com just to see if that had anything to do with it. I've tried every combination, but nothing works.

Can you please advise on what the configuration is supposed to look like so that Sentry and JIRA play nice again?

Thank you.

P.S. It'd been a while since I personally tried entering bugs from within Sentry so I only noticed this now. It could've been broken for a while but no one reported it. Thanks in advance for your help.

**Comment by salmanasiddiqui** [comment]
I have this same issue aswell.
During adding the JIRA creds to the plugin everything went smooth, but when I tried to create an issue from sentry into JIRA, I get 

> JIRA returned: Unauthorized. Please check your username, password, instance and project in your configuration settings.

Updating the creds on JIRA plugin sometimes fail aswell

**Comment by elianatixtrack** [comment]
Can anyone at Sentry help us with this?

**Comment by joecodenoise** [comment]
I am encountering this error as well. I use a hosted JIRA on atlassian and the JIRA user I'm using for integration is an admin. I am able to enable the JIRA plugin, and can link to existing JIRA issues, but cannot create new ones. I encounter this
 "Unauthorized: either your username and password were invalid or you do not have access"
message any time I attempt to search for a reporting user.

**Comment by sul4bh** [comment]
I ran into the same issue on hosted Sentry.

**Comment by vivekagarwal1984** [comment]
Any update or a workaround for the issue?

**Comment by elianatixtrack** [comment]
Nope. No response at all.

___

*Eliana Crema*
TixTrack, Inc.
eliana@tixtrack.com
844-380-9595 o
818-437-6915 m

**Comment by bharathrajbk** [comment]
I am running into the same issue. Any updates on this please?

**Comment by andrewbaxter** [comment]
Related: #142 #182 #190

**Comment by realjbarnard** [comment]
Have you tried explicitly granting "Create Issue" in JIRA to the user account (in that projects security scheme) that sentry is trying to log in with.  Even when set as a project admin, I was getting this same error.  Once I tried explicitly granting create issue, worked fine.

**Comment by elianatixtrack** [comment]
I'll give it a shot. Thanks.

___

*Eliana Crema*
TixTrack, Inc.
eliana@tixtrack.com
844-380-9595 o
818-437-6915 m
