### ISSUE TITLE
WrongBackend on GitHub Assosiate Identity

### ISSUE THREAD

**Issue by Skyross** [getsentry/sentry-plugins#284]
Hi!

I've met an error on Associate Identity with GitHub plugin. Same happens when trying to associate any other account (Asana for example). Did I miss some documentation about enabling plugins?

NOTE: Sentry and its plugins are 8.21.0 versions both.

![screenshot from 2017-12-04 17-07-35](https://user-images.githubusercontent.com/3192973/33556765-18ca49f0-d916-11e7-80a7-c438806a336d.png)

**Comment by Skyross** [comment]
Looks like there is a lack of the official documentation or somehow I missed a lot of steps.
So it's required to:
* **manually** [create GitHub OAuth Application](https://github.com/settings/applications/new) (`<URL_TO_SENTRY>/account/settings/social/associate/complete/github/` doesn't work from scratch as you may observe at screenshot of this issue)
* use generated tokens in Sentry configuration file at the server and follow [Plugins docs](https://github.com/getsentry/sentry-plugins#github)
* go to `http://<HOSTNAME>/organizations/<ORGANIZATION-ID>/repos/` and setup your repo giving permissions to authorize actions of that app

**Comment by xymz** [comment]
@Skyross I suffered with same issues. Thanks a lot.

**Comment by MikeDombo** [comment]
What do we set as the Authorization callback URL in the GitHub OAuth signup?

**Comment by Farkie** [comment]
I have this on the bitbucket one, but the docs don't mention any specific bitbucket config items. Any ideas?

**Comment by GuillaumeLachaud** [comment]
I am having the same with Asana integration.

**Comment by petermein** [comment]
Im running this problem aswell, any thing I can try?
