### ISSUE TITLE
404 when creating/linking issue to Pivotal Tracker

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry-plugins#285]
Status 404 (NOT FOUND) when trying to Create/Link an issue to Pivotal Tracker. It also looks like the API token may not be saved when saving the credentials since it only shows the grayed out example on page refresh:

## Saving API token
<img width="545" alt="screen shot 2017-12-06 at 2 38 03 pm" src="https://user-images.githubusercontent.com/20312973/33689217-7861b410-da93-11e7-8e50-9254ecf08898.png">

## After page refresh
<img width="543" alt="screen shot 2017-12-06 at 2 38 32 pm" src="https://user-images.githubusercontent.com/20312973/33689227-81142700-da93-11e7-9f50-4461431c6410.png">

**Comment by ChristinaGaitan** [comment]
I'm also having the 404 (NOT FOUND) response when trying to Create, Link and Unlink an issue.

**Comment by sleerssen** [comment]
Has there been any movement on this?  I'm trying to create a Sentry integration with Pivotal Tracker and it does not create new bugs/stories in PT when Sentry receives an error report.

**Comment by zspencer** [comment]
As an avid pivotal user, this is also a problem for us :(. I would be happy to pair with a dev advocate or something to drive getting pivotal up to speed with the rest of sentry's issue tracker situations.

**Comment by cmcaboy** [comment]
+1 The integration support for pivotal tracker seems to be lacking. This is an order winner for us. We will be switching if we can find another vendor that supports this integration.

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
