### ISSUE TITLE
OpsGenie plugin using deprecated API

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry-plugins#286]
v1 of the OpsGenie [Alert API](https://docs.opsgenie.com/v1.0/docs/alert-api-deprecated) is deprecated and we'll need to use the [new version]( https://docs.opsgenie.com/docs/alert-api).

cc @getsentry/workflow

**Comment by Mahoney** [comment]
I presume this hasn't gone live yet? Still listed as v0.1.0 on my https://sentry.io, and I can't get it to work, testing produces "There was an internal error with the Plugin" whether I use https://api.opsgenie.com/v1/json/alert or https://api.opsgenie.com/v2/alerts as the URL.

**Comment by lynnagara** [comment]
Thanks @Mahoney, sorry I'd forgotten to ship this change. Fixing that now.

**Comment by lynnagara** [comment]
https://github.com/getsentry/getsentry/pull/1635
