### ISSUE TITLE
How do you fill in the epic for JIRA?

### ISSUE THREAD

**Issue by danielsatanik** [getsentry/sentry-plugins#293]
I tried to add a sentry issue to JIRA, but it doesn't matter how I try to write in it it always gives back

`Error Communicating with JIRA (HTTP 400): String value expected as the Epic Key.`

I tried the epic name and the epic key, but both is not working.

**Comment by nnkteja** [comment]
Provide proper fields then you can get through.This is expected behavior, problem is from client side not from the server side.

**Comment by danielsatanik** [comment]
@nnkteja sorry but I don't understand. What fields should I provide? And you say the problem does not lie with the plugin, is that correct?

**Comment by nnkteja** [comment]
Epic Link in JIRA is a custom field like this (customfield_10001), I'm not sure about customfield_zzzzz in your JIRA, but for sure there exists some field like above.
To check your Epic Link in JIRA and all the fields available  [refer this section](https://docs.atlassian.com/software/jira/docs/api/REST/7.2.12/#api/2/field-getFields)
Make a GET /rest/api/2/field to your JIRA API
Payload should be like this::
{
 ..
"customfield_10001": <some valid epic link>
..
}
Reference:: https://docs.atlassian.com/software/jira/docs/api/REST/7.2.12/#api/2/issue-getIssue

**Comment by sunnyape** [comment]
I have the same problem. In my Jira, the Epic Link has the custom field value 10600, but when i try to set the value of that custom field via the REST API, no matter what value I supply, the response is always "String value expected as the Epic Key". I tried the Epic name, key, value etc and all the same.

My JSON post request body is 

$body = @{
                fields = @{
                    project = @{
                        key = $theProjectKey
                    }
                    issuetype = @{
                        name = 'Story'
                    }
                    description = $description
                    summary = $summary
                    customfield_10600 = @{
                        value = 'Test Epic'
                    }              
                }
            }

**Comment by nnkteja** [comment]
Hi @sunnyape, were you able to see the epic link in your Jira Ticket in UI. If you were able to see epic link in your Jira UI and `'Test Epic'` is your epic link and customfield_10600 is your Epic Link field, then directly assigning the value to customfield_10600 = 'Test Epic' is enough instead of what your JSON post request body contains.
The problem is with JSON you are providing. May be `'Test Epic'` is not your Epic link.

>  I tried the Epic name, key, value etc and all the same
-  Try Epic Link.

**Comment by sunnyape** [comment]
Thanks.

I found that the value for the field is set directly, not via a sub-value, so it's just plain:

    customfield_10600 = 'Test Epic'

Am able to set it correctly now.
