### ISSUE TITLE
Error Communicating with Bitbucket (HTTP 400): unknown error with self-hosted sentry

### ISSUE THREAD

**Issue by rstat1** [getsentry/sentry-plugins#294]
Trying to configure Bitbucket repo access, on a self-hosted sentry instance. This work without issue on the SaaS version.

I've got the keys in the right place, with permissions matching what the SaaS version wanted, and sentry is connected to my bitbucket account. Yet everytime I try adding a repo I get the above error. Doesn't matter if the repo is public or private (though I want to use a private repo).

Am using the latest released (docker) version 8.22.0

**Comment by luis-kaufmann-silva** [comment]
Same problem with me!

**Comment by guemidiborhane** [comment]
same thing for me +1

**Comment by firestalk** [comment]
Same problem here

**Comment by vassilis-karapatakis** [comment]
Same problem
