### ISSUE TITLE
ImportError: No module named distutils

### ISSUE THREAD

**Issue by sideboltconor** [getsentry/sentry-plugins#32]
Ubuntu 14.04 
Sentry 8.8.0

I'm trying to integrate the gitlab plugin but ran into an error. Am I missing a dependency? 

Collecting https://github.com/getsentry/sentry-plugins/archive/master.zip
  Downloading https://github.com/getsentry/sentry-plugins/archive/master.zip (128kB)
    100% |████████████████████████████████| 133kB 1.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-RMMpuX-build/setup.py", line 19, in <module>
        from sentry.utils.distutils import (
    ImportError: No module named distutils

**Comment by mattrobenolt** [comment]
This won't work with 8.8 and will need 8.9 when that is released next week.
