### ISSUE TITLE
Error Communicating with JIRA (HTTP 400): Number value expected as the Sprint id.

### ISSUE THREAD

**Issue by pauljeffreys** [getsentry/sentry-plugins#329]
Sentry seems to set up the JIRA tickets fine, and accepts the ID for the relevant Product Category. But when I try and use the IDs for the specific sprints it is giving me the title error message.

I am only entering a number, ie: 1211 or 1185 and nothing else. These ARE the IDs of the sprints i want to use for the tickets.

If I leave the Sprint field blank, then it does successfully add the ticket to our JIRA backlog, I then can move it to the correct sprint, but just looking to see if there is a reason it`s not accepting the IDs directly?

**Comment by pauljeffreys** [comment]
Is anybody able to help with this? Or point to an already solved question for this issue?

**Comment by jcasner** [comment]
I'm having the same problem. Ideally, I'd like to able to search for a sprint by name, too, and have Sentry pull back the correct ID

**Comment by amigold** [comment]
same here
