### ISSUE TITLE
clubhouse acceptance test broken

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-plugins#335]
![screen shot 2018-03-20 at 11 10 46 am](https://user-images.githubusercontent.com/23610/37674144-6244486c-2c2f-11e8-858a-6d8a9be2b76b.png)

**Comment by miketheman** [comment]
As of today, I tried against be5fdedf095ea2f074dcc88b3f89d03d8b3f335a and `sentry, version 9.1.0.dev0 (eb137de6fb92)` and the pytest test passed.

I'm not sure I known where the snapshots go during the test, so I can't find where these images might be located.
