### ISSUE TITLE
Support Jira Server?

### ISSUE THREAD

**Issue by 0xF6** [getsentry/sentry-plugins#340]
Why only jira cloud?

**Comment by BenPorat** [comment]
Hey Yuuki,

From my understanding it's not suppose to be for JIRA Cloud only,
You need to whitelist Sentry IP https://docs.sentry.io/ip-ranges/

Then follow the second instruction:
https://docs.sentry.io/integrations/jira/#jira-issue-creation-from-sentry

**Comment by jonty-comp** [comment]
I thought it only supported JIRA cloud - but i've just found that if I just write the local JIRA URL in with the user/pass of the bot account in JIRA, it works fine!
Make sure to not put a trailing / on the JIRA URL as this breaks links from Sentry.

**Comment by markstory** [comment]
Closing as Jira-Server support via an integration has been recently enabled.  The [docs can be found here](https://docs.sentry.io/workflow/integrations/global-integrations/jira-server/)
