### ISSUE TITLE
feature request: Clubhouse plugin to search globally or support multiple projects

### ISSUE THREAD

**Issue by mkj28** [getsentry/sentry-plugins#344]
Looks like the Clubhouse plugin only searches within the specified project. Would be nice for it to either search globally (best) or be able to specify multiple clubhouse projects (with one of them being default for newly created tickets).

We have a story in Clubhouse that does not show up in plugin results, just because it is in a different project. See attached. 

![2018-03-29_1050](https://user-images.githubusercontent.com/2279299/38104938-93080cb0-333f-11e8-9bc8-3e9486104564.png)

**Comment by ssalka** [comment]
+1, this is an important feature for my team. We use a monorepo on GitHub, and run only 1 project in Sentry, but we have many projects in ClubHouse (product, platform, analytics, ...) that all tie into the same Sentry project.

The obvious workaround for an end-user creating a new story is to just change the project in ClubHouse after adding, but this is 1) annoying, and 2) doesn't address linking to existing issues in other projects.

**Comment by mkj28** [comment]
@miketheman wondering if you came across this one?

**Comment by miketheman** [comment]
@mkj28 I hadn't, thanks for pointing it out. 

In thinking about this, it seems like adding a config flag to search all projects might work, default to search only the configured project might solve the problem.

I think keeping the project value required makes sense as that makes it explicit on where new stories go, even if that is then manually duplicated across multiple sentry projects.

Does that sound like it would solve the need?

**Comment by mkj28** [comment]
At least for us - that would work great. We can search all projects if flag enabled, and keep the project listed as the default one for new stories.... yes.

**Comment by miketheman** [comment]
I believe the linked PR will solve the linking case - I don't know how common the case @ssalka brings up with a mono-sentry approach to create new stories is - but this ought to cover searching for existing stories.
