### ISSUE TITLE
Plugins not showing up

### ISSUE THREAD

**Issue by bhanga-manish** [getsentry/sentry-plugins#347]
Hi,
I installed sentry plugins using command "pip install sentry-plugins" and then i ran "sentry upgrade"
It shows that slack is already in synced but when i visit the page the plugins are not showing up.
I not encountering any error whatsoever

**Comment by thetemplar** [comment]
Hey, I have the same problem. 

pip install sentry-plugins
sentry upgrade
and reboot

does not work. What am I missing?

**Comment by talvespe** [comment]
@thetemplar Did you figure out? 
I'm using on-premise v9.0  and Integrations session is not shown

**Comment by thetemplar** [comment]
Yes, it was missing something obvious, but sadly I cannot remember what it was, because it is half a year ago, sorry :(
