### ISSUE TITLE
PagerDuty integration not working

### ISSUE THREAD

**Issue by vshia** [getsentry/sentry-plugins#356]
Hi,

I've setup the Sentry+PagerDuty integration following the instructions posted [here](https://www.pagerduty.com/docs/guides/sentry-integration-guide/).  But when I click "Test Plugin" in Sentry (image below)
<img width="608" alt="screen shot 2018-05-03 at 15 51 39" src="https://user-images.githubusercontent.com/401047/39606373-f737b490-4ee9-11e8-98b8-d407a47c2342.png">
 I receive an event in PagerDuty as expected.

However, when I actually trigger an event on my servers, I do get an issue in Sentry but don't get one in PagerDuty, indicating that somewhere along the way, the Sentry - PagerDuty integration isn't working as expected.

Originally, I thought it had to do with the fact that my Sentry integration key is v2 and v1 keys have been [deprecated](https://v2.developer.pagerduty.com/docs/v1-rest-api-decommissioning-faq) but manually firing the event off a test event with my v2 key on [this web form](https://v2.developer.pagerduty.com/docs/trigger-events) works.

In terms of potential breaking points in the flow, it looks like:
- The `Servers -> Sentry` seems fine
- The `Sentry -> PagerDuty` ???
- The `Test on Sentry -> PagerDuty` seems fine

This leads me to think that something with the plugin is broken. I thought it had to do with the change from v1 to v2 but according to [PagerDuty](https://v2.developer.pagerduty.com/v2/docs/events-api), the Events API, which I think the Sentry-PagerDuty plugin uses, wasn't modified. Has anyone else run into this issue? If so, how did you fix it?

Thank you,

**Comment by thraxil** [comment]
I'm seeing this as well. PagerDuty is expiring their v1 API in a few weeks. I generated a new API key for v2 and put it into Sentry and get "There was an internal error with the Plugin" and no PagerDuty alert is created. Projects that still have the v1 API key are still working.

**Comment by taylor-cedar** [comment]
I am not getting this as well on version 9.0.0. Is there a fix for this?

**Comment by david-bjelland** [comment]
Still seeing this issue, despite the fix referenced above being merged; followed same guide as OP, and same steps to verify that the `Servers -> Sentry` and `Test on Sentry -> PagerDuty` are working as expected. Using brand-new pagerduty integration keys as well.

Any working hypotheses out there on where the disconnect might be?

**Comment by davidchua** [comment]
I'm on `9.1.2` both `sentry` and `sentry-plugins`. I've added the Pagerduty integration on my sentry, and when I click on "Test Plugin", I get a

```
Test Results:
"No errors returned"
```

`sentry-web` logs shows:

```
03:08:32 [INFO] sentry.eventstream.base: post_process.skip.raw_event (event_id=58L)
03:08:33 [INFO] sentry.plugins.pagerduty: notification-plugin.notify-failed. (plugin=u'pagerduty' error=u'Error Communicating with PagerDuty (HTTP 400): Event object is invalid')
```

On Pagerduty, I've created the integration with `Sentry` app type.

**Comment by plux-kivra** [comment]
@davidchua I have the exact same setup and get the same error.

**Comment by thillmfg** [comment]
@davidchua same situation, I've tried using an integration key for v1 and v2 in my PagerDuty service.
Both fail with the same 400 error in the logs, but the Sentry plugin frontend says Test Results:
"No errors returned"

**Comment by BYK** [comment]
This is very likely to be fixed on latest master. As this repo is now deprecated and merged into getsentry/sentry, I'll be closing this issue. Feel free to open a new issue there or submitting a new topic to [the forums](https://forum.sentry.io) if you are still experiencing this.
