### ISSUE TITLE
automatically closing jira issues

### ISSUE THREAD

**Issue by ekimia** [getsentry/sentry-plugins#374]
Love the sync, but its extra work having to close the sentry and then jira issue. Is there a way to automatically close them out from 1 way or another?

**Comment by TanvirAlam** [comment]
@ekimia did you find any solution? please let me know, I am also looking at this issue.

**Comment by ekimia** [comment]
@TanvirAlam no dice :(

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
