### ISSUE TITLE
VictorOps Plugin seems to be lacking basic information about the alert

### ISSUE THREAD

**Issue by NeckBeardPrince** [getsentry/sentry-plugins#378]
![untitled](https://user-images.githubusercontent.com/6558867/42905369-6af66cac-8a9d-11e8-941b-104e3deeb0da.png)

By looking at the alert above I have no idea at all which project, environment, site or anything is having the reported problem. It's boarder line useless.

Also, there is no documentation on it at all.
https://docs.sentry.io/integrations/

**Comment by mikel-arena** [comment]
@NeckBeardPrince The url to the issue has been added to the victorops alert here: #431

**Comment by markstory** [comment]
Closing as the newly added URL should make provide more context.
