### ISSUE TITLE
JIRA/BitBucket Server Support

### ISSUE THREAD

**Issue by l0nax** [getsentry/sentry-plugins#383]
Hey,
Is there any possibility to use the Sentry JIRA and BitBucket Plugin with the Self-Hosted Instances?

How can I change/ configure the URL's and how do I install the Plugins to the JIRA and BitBucket servers?

**Comment by nilson-aguiar** [comment]
https://github.com/getsentry/sentry-plugins/issues/197

**Comment by mhauens** [comment]
Would be nice to have something like the Jira plugin -> Instance URL to selfhosted BitBucket.
