### ISSUE TITLE
[slack] Environment filtering

### ISSUE THREAD

**Issue by koleror** [getsentry/sentry-plugins#391]
Hello guys,
I would love to start using the new environment tag feature of sentry, but cannot at the moment as it is apparently not possible today to filter the slack notifications for a single environment.

The purpose is to be able to have different channels for prod, sandbox and dev environments, which is done today using different projects.
The environment tags are not even displayed on the slack notifications.
Did I miss something or is it a missing feature?

**Comment by firepunch** [comment]
> You can configure the alerts which are generated via project settings > rules

https://github.com/getsentry/sentry-slack/issues/46
