### ISSUE TITLE
How to set Epic link

### ISSUE THREAD

**Issue by montogeek** [getsentry/sentry-plugins#414]
Hi!

What is the correct value you should set in Epic link when creating an issue?
Values I have tried without success:

- `customfield_xxx`
- `REM-XXX`
- `Epic name`
- `key:REM-XXX`
- `key:Epic name`
- `value:REM-XXX`
- `value:Epic name`

Thanks!

**Comment by montogeek** [comment]
@BYK This was updated somewhere?

**Comment by BYK** [comment]
Hi @montogeek - closed this issue as part of a bulk operation as this repo is now deprecated and the issue was quite stale. I'd also recommend using [the forums](https://forum.sentry.io) to get answers to configuration issues like this.

Sorry for the trouble!
