### ISSUE TITLE
Documentation on adding bitbucket integration

### ISSUE THREAD

**Issue by rvanlaar** [getsentry/sentry-plugins#417]
Hi, 

Thanks for the great work.

I'm running sentry self hosted. I'm currently on a wild goose chase trying to find how to integrate bitbucket repos with Sentry.

Could information about this be added to the documentation?

Thanks

**Comment by MickaelBergem** [comment]
I am also facing this issue. @rvanlaar did you manage to get it working? My next step is to dive into the source code to see what's missing (currently trying to add a bitbucket repo leads to a Sentry crash).

**Comment by rvanlaar** [comment]
@MickaelBergem I'm not sure. What I got working was creating an issue on bitbucket, directly from Sentry.
