### ISSUE TITLE
Could not determine sentry version or build

### ISSUE THREAD

**Issue by aswinm** [getsentry/sentry-plugins#42]
When I try doing a pip install for sentry-plugins, it always fails with the error:

     Could not determine sentry version or build. 

Installing other plugins like sentry-slack, sentry-bitbucket works fine. Only sentry-plugins is failing

**Comment by chauffer** [comment]
I get this as well:
```    running build_assets
    using node (v6.7.0) and npm (3.10.3)
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz
    node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.7.0 (node-v48 ABI) (falling back to source compile with node-gyp)
    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
    pulled version information from 'sentry' module
    building assets for sentry-plugins v0.1.2 (build UNKNOWN)
    Could not determine sentry version or build
```

**Comment by aswinm** [comment]
But on cloning the repo manually and running `python setup.py install` works fine.

**Comment by joelwigley** [comment]
I'm having this same problem on a fresh install of Sentry. 

@aswinm, can you briefly elaborate on your manual installation method? I'm pretty new to Sentry and even Python in general. I'm wondering if I need to clone and install from the directory Sentry is installed?

**Comment by aswinm** [comment]
@joelwigley The problem is, Sentry 8.10 has a set of new models and the master in sentry-plugins already uses those models. So you get those errors. It will work if you upgrade sentry to 8.10, which is still a dev version.

Check this issue: #48

**Comment by mattrobenolt** [comment]
This repository is absolutely brand new and hasn't yet really been intended for use outside of us. Which is why it's being developed very closely to master, etc.

With 8.10, we're going to be tagging and releasing this this to go with it to work against something stable.

So just hang in there for now.

**Comment by joelwigley** [comment]
@mattrobenolt Is there another repository we can use for plugins in Sentry 8.9.0 in the meantime?

The documentation links to https://github.com/getsentry/sentry-github but I saw the deprecated information and clicked through to this one.

**Comment by mattrobenolt** [comment]
You should use that still. Looks like we put up deprecation a bit premature. :(

**Comment by aswinm** [comment]
@mattrobenolt For you guys to look into this issue, there is some problem in determining sentry's build number.
The installation runs fine when you set `SENTRY_BUILD=9` variable while calling pip install

**Comment by mattrobenolt** [comment]
We already fixed the issue upstream fwiw. https://github.com/getsentry/sentry/commit/16842059d3c202bccbaab6ec81e3cae09db087d3

**Comment by aswinm** [comment]
Great... Closing this issue
