### ISSUE TITLE
Gitlab integration: 404 response

### ISSUE THREAD

**Issue by v0lume** [getsentry/sentry-plugins#423]
same problem described in:
#34 #117 

the problem is that when we specify repository name as "group_name/repo_name" - receiving 404 unknown error from sentry.

as i understand, the problem is in "/" in project name as described in [docs](https://gitlab.com/help/api/projects.md#get-single-project)

i tried to replace / with %2F but now receiving "404 repo not found".
i tried to use just project id as project_name - it works perfectly except when i create an issue and trying to navigate to it from sentry - im receiving also 404 error from gitlab cause it don't use project_id in routing.

<img width="522" alt="untitled" src="https://user-images.githubusercontent.com/5075100/48714756-6eff4100-ec24-11e8-9435-d67a8682d385.png">

**Comment by MRigal** [comment]
This is actually pretty simple, although super wired @markstory 

After updating the GitLab API from v3 to v4, the widget was not updated. Instead of entering the Repository Name, you should enter the project ID there and it works :-)

**Comment by markstory** [comment]
@MRigal I'm not sure we've done any testing of gitlab v4 + this plugin. I do know that the organization integration works with the latest GitLab releases though.

As for a v10 release, there aren't any concrete timelines just yet. This [forum post](https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622) is the thread to follow though.
