### ISSUE TITLE
Error integrating while Sentry with Youtrack

### ISSUE THREAD

**Issue by markstory** [getsentry/sentry-plugins#439]
_From @rajesh-dcis on January 10, 2019 10:27_

We have already integrated sentry issues with youtrack and which was working fine for a period of time and all of a sudden it stopped working. When I checked the integration we are receiving an error while accessing the plugins. Screen shot attached for your reference.

_Copied from original issue: getsentry/sentry#11458_

**Comment by rajesh-dcis** [comment]
@markstory Did you get a chance to look on this issue.

**Comment by markstory** [comment]
No I've not. I've never used youtrack and am not in a good position to figure out what could be wrong with it.

**Comment by Egregors** [comment]
@rajesh-dcis I got the same problem. Looks like something wrong with frontend part of the plugin. Solve it just disable all ad blockers on for sentry domain.

**Comment by rajesh-dcis** [comment]
@Egregors I do not find an option on how to disable "ad blockers" on my dashboard.

**Comment by Egregors** [comment]
@rajesh-dcis I mean turn off Ad Blockers in your browser

**Comment by rajesh-dcis** [comment]
@Egregors Add blockers wasn't enable on the browser which I use. I have attached the screen shot of what happens as we enabled youtrack plugin. It requests me to submit crash report which I have already submitted.
![you](https://user-images.githubusercontent.com/15102350/52837553-2cf77580-3115-11e9-928c-aac548222820.png)

**Comment by Egregors** [comment]
@rajesh-dcis yep, I had absolutely the same behavior and I still pretty sure it is the frontend problem. Did you try different browsers? Be sure you disable any browser plugins who may change the DOM on the Sentry page.

**Comment by rajesh-dcis** [comment]
@Egregors Let me try that and keep you posted.
