### ISSUE TITLE
Unable to create GitLab integration

### ISSUE THREAD

**Issue by enyo** [getsentry/sentry-plugins#450]
When I try to link my project, everything works until the last step where I get:

> The requested GitLab group could not be found.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/133277/53725415-40704380-3e6c-11e9-970b-214149c37b5a.png">

The link to my GitLab instance worked fine, and I'm 100% certain that I entered the right `group/subgroup` combination (as in https://gitlab.com/group/subgroup)

(The repository I'm linking is private, but since I'm creating an Application API access specifically for it, I don't see this being the problem)

**Comment by enyo** [comment]
Not sure if this is the right repo so I also created it here: https://github.com/getsentry/sentry/issues/12273

**Comment by markstory** [comment]
Closing as a duplicate.
