### ISSUE TITLE
[JIRA] Autocomplete for reporter "Loading failed"

### ISSUE THREAD

**Issue by cloudbeds-jack** [getsentry/sentry-plugins#455]
![image](https://user-images.githubusercontent.com/43075057/54714399-1a0a0380-4b0e-11e9-8a00-b5e4fcfbec32.png)

Looking more into this error I found this error:
`AttributeError: 'SequenceApiResponse' object has no attribute 'xml'` Which appears to be talking about line 354 in sentry_plugins/jira/plugin.py `for userxml in autocomplete_response.xml.findAll("users"):`

I don't think anyone changed anything in our on-premise install nor in Jira config, so wondering if anyone else has/had this issue and/or knows how to troubleshoot/solve it.

Tried doing curl to the url, and it does return a normal looking json object, even though request was for xml (according to request/response headers.

Raw error:
`AttributeError: 'SequenceApiResponse' object has no attribute 'xml'
  File "sentry/api/base.py", line 87, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 170, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/plugins/endpoints.py", line 44, in get
    return self._handle(request, group, *args, **kwargs)
  File "sentry/plugins/bases/issue2.py", line 34, in _handle
    return getattr(self.plugin, self.view_method_name)(request, group, *args, **kwargs)
  File "sentry_plugins/jira/plugin.py", line 354, in view_autocomplete
    for userxml in autocomplete_response.xml.findAll("users"):`

**Comment by NoNalTrX** [comment]
Having the same issue here, the reason (I think) is because jira api return on JSON. there is no way to have XML back from JIRA api.

**Comment by markstory** [comment]
I think this will be resolved by #456

**Comment by NoNalTrX** [comment]
looks like the PR fix has been merged on master, do we know when the next release is?

**Comment by markstory** [comment]
@NoNalTrX If you're using sentry.io, these changes should already be live. If you're using on-premise [this forum post](https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622/11) is the latest news.

**Comment by undernewmanagement** [comment]
I know this has already been merged, but I was able to get it working in my standard-ish deployment of the onpremise using docker-compose by backporting the regex fix into the plugin.py.

https://gist.github.com/undernewmanagement/1e85d194a4a57bd2c8ebd4f4d398b877

This way I don't have to wait for a new version.
