### ISSUE TITLE
Impossible to use GitLab integration if repository is owned by user

### ISSUE THREAD

**Issue by remram44** [getsentry/sentry-plugins#458]
Obviously if your repository is owned by a user, not a group, there is no group to enter in the "GitLab Group Path" text box. Entering my user name fails, so does username/project, or entering nothing.

**Comment by markstory** [comment]
We intentionally aimed the new integration at group level repositories as that was what most of the users we had talked to use. Using both groups and users would add more complexity to the setup, which we wanted to avoid as the GitLab configuration is already a complex process.

We may change this in the future, but for now the integration requires a group.

**Comment by remram44** [comment]
UX-wise, I don't think supporting both username and group is difficult. They share the same namespace on GitLab (`gitlab.com/<group_or_username>/project`).

I am also confused as to why you need a user or group name and not the path to an actual project.

In any case, it would be nice to have some kind of warning somewhere that only groups are supported, so that we are not confused when it doesn't work, and don't spend time trying different inputs. Bonus points if this warning is at the very beginning, so we don't bother creating the application and copying the keys.

**Comment by markstory** [comment]
> I am also confused as to why you need a user or group name and not the path to an actual project.

The reason for this is that the integration needs a 'scope' to operate in. That scope is used to autocomplete projects and issues. Linking to a single repository would make using the gitlab integration more tedious for teams with more than a single repository, as each repository would require more setup. We have opted to optimize the experience for use cases that involve more than a single repository, as that is what our users and customers have asked for.

> In any case, it would be nice to have some kind of warning somewhere that only groups are supported,

Both the documentation and setup help mention group specifically, and never user. Do you have any suggestions on how we could make the instructions clearer?

**Comment by remram44** [comment]
You could mention explicitly that if my repo is owned by a user, I need to move it to a group. I had assumed that a single user was an acceptable group.

**Comment by cawa-93** [comment]
Looks like no changes at this time. Are you working towards integrations with out-group repositories? Has it been decided to ignore this type of repository?

**Comment by markstory** [comment]
@cawa-93 at this time we are not planning to change this. We haven't come across many organizations that operate out of single user accounts in our saas business, which is what drives most product development priorities.

**Comment by remram44** [comment]
That sounds reasonable to me. I also operate out of groups, but I can see a lot of people trying it out beforehand. It would be good if you could make it clear in the UI that it needs to be a group.

**Comment by markstory** [comment]
@remram44 The field is called 'group path'. Is there a more specific term I can use?

**Comment by remram44** [comment]
I would recommend a warning over [here](https://github.com/getsentry/sentry/blob/39a3d72a0f18127e3eae333183b3ebfc2de54871/src/sentry/integrations/gitlab/integration.py#L29), for example:
```diff
-Connect your Sentry organization to your GitLab instance or gitlab.com, enabling the following features:
+Connect your Sentry organization to an organization on your GitLab instance or gitlab.com, enabling the following features:
```

and/or at the least [here](https://github.com/getsentry/sentry/blob/104c1965c35258f85920d0c16fae6194e96133d0/src/sentry/templates/sentry/integrations/gitlab-config.html#L52), for example:
```diff
-  <p>{% trans "You'll also need to be a maintainer or owner in GitLab." %}</p>
+  <p>{% trans "You'll also need to be a maintainer or owner in the GitLab organization. Projects owned by users are not supported." %}</p>
```

**Comment by BYK** [comment]
Closing as this repo is now deprecated (merged into getsentry/sentry) and we are unlikely to address this in the short term. It is on our backlog tho and if anyone wants to submit a PR addressing this, they are more than welcome to do so over at getsentry/sentry.
