### ISSUE TITLE
Slack: "Select Assignee..." only lists teams, not users

### ISSUE THREAD

**Issue by agis** [getsentry/sentry-plugins#463]
After upgrading our on-premise instance to 9.1.0 (from 9.0.0) we noticed that on the "Select Assignee.." select box in Slack, only the teams are listed - the users are missing.

From Sentry's web UI, we can normally assign issues to individual users.

Any ideas why this might have happened? Thanks

**Comment by BYK** [comment]
Not sure what might be broken but it may be related to this: https://github.com/getsentry/sentry/issues/9004

As this repo is now merged into getsentry/sentry, please file a new issue there or post a new topic on [the forums](https://forum.sentry.io) if you are still having issues.
