### ISSUE TITLE
Phabricator: "One or more PHIDs were invalid for ownerPHID"

### ISSUE THREAD

**Issue by agis** [getsentry/sentry-plugins#466]
We're on 9.1.0 and we've noticed that if an assignee is not set, then the task creation throws an error with the following message.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/827224/56414967-efd66d80-6294-11e9-9f10-a4ac76189b0a.png">

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
