### ISSUE TITLE
[Jira Server] Assignee and Reporter get visually reset on ticket creation form error

### ISSUE THREAD

**Issue by philiplb** [getsentry/sentry-plugins#472]
Hi,

I create a Jira ticket from the Sentry issue and fill some wrong information in the form. For example, I choose the type "Sub Task", fill the reporter and assignee and then try to submit that.
The form validation fails because "Issue type is a sub-task but parent issue key or id not specified." which is completly fine.
But the UI fields of the reporter and the assignee loose their content visually.
I now correct the type and choose bug and submit the form again without setting the reporter and assignee again. The ticket gets created in Jira and the reporter and assignee are correctly set, so the Sentry ticket creation form just had a visual glitch.

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
