### ISSUE TITLE
[Jira Server] Add the possibility to create unassigned tickets

### ISSUE THREAD

**Issue by philiplb** [getsentry/sentry-plugins#474]
Hi,

in our scrum workflow, newly created tickets don't have an assignee. Currently, if I create a ticket from Sentry, I can't set this. If I leave out this field, the ticket gets assigned to the Jira project default assignee. And I can't enter "Unassigned".

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
