### ISSUE TITLE
[Jira Server] Unlucky Default Type

### ISSUE THREAD

**Issue by philiplb** [getsentry/sentry-plugins#476]
Hi,

whenever I create a Jira ticket from Sentry, the type is set as "SubTask" which will lead to the form error "Issue type is a sub-task but parent issue key or id not specified." and it is semantically wrong.
Is there any way to have the type "Bug" as default?

**Comment by markstory** [comment]
>  Is there any way to have the type "Bug" as default?

Not right now there isn't.

**Comment by philiplb** [comment]
Thank you for the fast answer. I understand.

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
