### ISSUE TITLE
Can't to configure GitHub integration

### ISSUE THREAD

**Issue by artful88533** [getsentry/sentry-plugins#477]
Hello!
Sentry 9.1.1

Associate your account with GitHub (if you haven't already) via Account -> Identities.
When I try to do above step from instruction, I see this:
![image](https://user-images.githubusercontent.com/19188399/57571456-427bf300-7417-11e9-863f-c8c664d802f0.png)

I don't understand how to associate my account with GitHub. Am I missing something?
Please help me.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
