### ISSUE TITLE
Stable version of sentry-plugins for sentry 8.9.0

### ISSUE THREAD

**Issue by aswinm** [getsentry/sentry-plugins#48]
Hi,
   Currently, the latest change in the master for Github, which includes the Commit model of sentry, breaks in sentry 8.9.0. Even archive/master.zip also has the new code and so I am not able to install sentry-plugins in my server. 

  Can I get a stable build of sentry-plugins?

**Comment by joelwigley** [comment]
I too would like to be able to install these plugins into 8.9.0. Installation can be forced (to get around the unknown build version error) but the missing Commit model causes the web server to fail.

I tried using the old deprecated plugin for HipChat but it does not work correctly.

I guess I've come in during a bit of a transition period which is unfortunate. Hopefully this can be solved soon!

**Comment by bsergean** [comment]
Looks like sentry-plugins is now available from PyPI.

**Comment by mattrobenolt** [comment]
Yeah, 8.10.0 has been published and will be released in tandem with sentry server so there shouldn't be any question about compatibility in the future.
