### ISSUE TITLE
Asana Integration: Internal Server Error

### ISSUE THREAD

**Issue by DanEngelhardt** [getsentry/sentry-plugins#483]
Hi,
I'm trying to link my sentry onpremise installation to our companies asana. 
Whenever I click on "Associate Identity" on the page `/settings/my-org/my-proj/issue-tracking/` under "asana" it gives me an internal server error (500).

`docker logs sentry-onpremise_web_1` gives me the following information:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social_auth/decorators.py", line 27, in wrapper
    raise WrongBackend(backend)
WrongBackend
12:37:59 [ERROR] django.request: Internal Server Error: /account/settings/social/associate/asana/ (status_code=500 request=<WSGIRequest: GET u'/account/settings/social/associate/asana/?next=%2Fsettings%2Fmy-org%2Fmy-project%2Fissue-tracking%2F'>)
```

Version in the footer says "Sentry 9.0.0" if that helps

EDIT 1: I dont know what to do or what this "WrongBackend" is supposed to tell me since everything else works without any problems - Sentry is running and receives events from our servers.

EDIT 2: I'm running sentry behind an dockered nginx-proxy, which is the only thing that comes to my mind when thinking of something that could be related to "WrongBackend". But the nginx-logs doesnt show any errors

EDIT 3: I opened the same issue in the main repo, since it seems that none of the devs are reading here:
https://github.com/getsentry/sentry/issues/11022

**Comment by grv231** [comment]
@DanEngelhardt Did you finally find any solution to this? Ran into the exact same problem today (on-premise setup). Is there some config that needs to be built into docker image (apart from plugin name in requirements.txt file)?

**Comment by DanielEngelhardt** [comment]
@grv231 I didn't find a solution for it, unfortunately. At some point I just stopped investigating this any further. 
In case you find a solution please let me know.

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
