### ISSUE TITLE
[JIRA integration] Authorization not working 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [getsentry/sentry-plugins#491]
Hi Team. 

We are using sentry-jira integration and it has been working smoothly until when it stopped working last week. When i try to update configs, I am getting error "Unauthorized: either your username and password were invalid or you do not have access". Can someone help me ?

**Comment by markstory** [comment]
Have you made sure that your username and password are correct?

**Comment by HIMANSHU-ELIGIBLE** [comment]
Yes, I could login with same password and email to site. I also have confirmed that username is correct. 
Also, same credentials have been working until last week.

**Comment by markstory** [comment]
Are you using sentry.io or a self-hosted sentry instance?

**Comment by HIMANSHU-ELIGIBLE** [comment]
Hi @markstory we are using hosted sentry instance.

**Comment by markstory** [comment]
Have you considered moving to the organization level jira-cloud or jira-server integrations? They offer similar features and will be supported in the future whereas the project plugin is no longer supported.

**Comment by HIMANSHU-ELIGIBLE** [comment]
@markstory sure I will give it a try and will let you know how it works.

**Comment by MaicolBen** [comment]
It happens to me as well with sentry.io

**Comment by BYK** [comment]
Closing as this repo is now deprecated. If you are having this issue on sentry.io, I strongly recommend creating a support ticket. If not, you may file a new issue over at getsentry/sentry or use [the forums](https://forum.sentry.io/) for more discussion.
