### ISSUE TITLE
[GitHub] Label GitHub issues created (linked) by Sentry

### ISSUE THREAD

**Issue by aramir** [getsentry/sentry-plugins#509]
it would be just awesome if sentry can automatically create and assign it's own label to a GitHub issue to mark that the issue is linked to/created from sentry. (Should probably be an option)

Similar to how ZenDesk (as well as other integrations) do it now. Here is a sample of an issue that was created from ZenDesk using TissueApp integration:

![image](https://user-images.githubusercontent.com/2984000/64502595-d5b91e00-d27b-11e9-826a-bc3809f1ed4c.png)

(ZenDesk label was automatically created by the integration and assigned to that issue)

**Comment by magroski** [comment]
This is a really interesting feature that helps triaging issues/bugs that need to be fixed.

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. You can follow the mirror issue there: getsentry/sentry#14751
