### ISSUE TITLE
[Asana Integration] Unable to create issues anymore

### ISSUE THREAD

**Issue by berlix** [getsentry/sentry-plugins#510]
When attempting to create an Asana issue from a Sentry issue, since recently we only get the error message "Error Communicating with Asana (HTTP 400): workspace: Not a valid GID type: number", and no Asana issue gets created.

Judging by the error message, I suspect this might have to do with Asana's change from numerical to string IDs: https://forum.asana.com/t/asana-is-moving-to-string-ids-updated-with-revised-timeline/29340

**Comment by berlix** [comment]
Related issue on the `sentry` repo: https://github.com/getsentry/sentry/issues/14520

**Comment by markstory** [comment]
This looks like it could be fixed by #508

**Comment by BYK** [comment]
This repo is now merged into getsentry/sentry so please file an issue there if you still have this issue.
