### ISSUE TITLE
Configuring Slack Integration for Sentry On-Premise

### ISSUE THREAD

**Issue by PaarthB** [getsentry/sentry-plugins#511]
I have created a new Slack app for our Sentry On-Premise and installed it by providing the credentials created from the app. But I am still not able to send alerts through. I have added the bot to the channel I am targeting but it still doesn't help. I get the error: 

`The slack resource "sentry-ops" does not exist or has not been granted access in the <workspace_name> Slack workspace.
`

What have I not done correctly? I followed this guide step by step https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

I have added everything except App Unfurl Domains.

**Comment by EvanPurkhiser** [comment]
See the thread here: https://github.com/getsentry/sentry/issues/7897. Specifically this comment: https://github.com/getsentry/sentry/issues/7897#issuecomment-500616932
