### ISSUE TITLE
Add GitLab entire root instead of a group

### ISSUE THREAD

**Issue by sherpya** [getsentry/sentry-plugins#515]
I'm trying to add GitLab CE (hosted) integration, we have a lot of groups and projects are spread around them
There is a simple way to use the root namespace as `GitLab Group Path`.
I would be happy to not create 30+ different integrations by hand.

**Comment by BYK** [comment]
This is now being addressed in getsentry/sentry#15188. As this repo is now deprecated, closing the issue.
