### ISSUE TITLE
GitLab Allow user impersonation when creating issues

### ISSUE THREAD

**Issue by aexvir** [getsentry/sentry-plugins#530]
I understand that it might be a security risk, but in environments secured enough this might be useful, that way the user opening the issue could be the user that actually triggered the action from Sentry's UI.

GitLab allows this using admin users and tokens with [`sudo` scope](https://docs.gitlab.com/ee/api/#sudo)

It will probably require trying to find the user in GitLab by email, and if found then use the `sudo` attribute to make the action as that user.

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this that said it may not get merged as this feature request sounds a bit controversial to me.
