### ISSUE TITLE
Jira Issue Creation - ability to set the Reporter automatically to the sentry logged in user

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-plugins#71]
Our usernames are the same for our sentry and our jira instance, so it would be ideal if we could pre-populate the "Reporter" field with the currently named field when creating an issue in JIRA.

Maybe we could first do a request to the JIRA backend to see if the user is known (like the requests which are being done for gathering a list of users for auto-complete).

**Comment by BYK** [comment]
Closing as this repo is now deprecated and merged into getsentry/sentry. Feel free to submit a PR there if you are interested in implementing this.
