### ISSUE TITLE
JIRA Add On - configure self-hosted sentry URL

### ISSUE THREAD

**Issue by aldenquimby** [getsentry/sentry-plugins#75]
When I try to configure the Sentry JIRA Add On, I see:

  ![image](https://cloud.githubusercontent.com/assets/2145098/19975705/59a93f2a-a1c3-11e6-93c6-ad6a02014203.png)

And the `Sign In To Sentry` button takes me to https://sentry.io.

Is there any way for me to configure the JIRA add on to work with my self-hosted sentry server, instead of sentry.io?

**Comment by Awk34** [comment]
@aldenquimby see https://github.com/getsentry/sentry-plugins/issues/123#issuecomment-272548905
