### ISSUE TITLE
Sentry upgrade fails on CREATE TABLE "sentry_hipchat_ac_tenant"

### ISSUE THREAD

**Issue by JeanFred** [getsentry/sentry-plugins#78]
I have tried upgrading my on-premise setup to 8.10.

(There was a bit of confusion as I had missed the memo about the plugins being consolidated into one pre-installed package (did I miss that in the release notes?))

Eventually `sentry upgrade` fails with 
```
FATAL ERROR - The following SQL query failed: 
SQL: CREATE TABLE "sentry_hipchat_ac_tenant" ("id" varchar(40) NOT NULL PRIMARY KEY, "room_id" varchar(40) NOT NULL, "room_name" varchar(200) NULL, "room_owner_id" varchar(40) NULL, "room_owner_name" varchar(200) NULL, "secret" varchar(120) NOT NULL, "homepage" varchar(250) NOT NULL, "token_url" varchar(250) NOT NULL, "capabilities_url" varchar(250) NOT NULL, "api_base_url" varchar(250) NOT NULL, "installed_from" varchar(250) NOT NULL, "auth_user_id" integer NULL)
Error in migration: hipchat_ac:0001_initial
```

**Comment by mattrobenolt** [comment]
Dang. I assumed nobody had the old Hipchat AC plugin installed. Yeah, this is the one issue we had when merging. Lemme get you command to run to fix it. You just need to fake the migration.

**Comment by mattrobenolt** [comment]
Can you try running:

```
$ sentry django migrate --fake hipchat_ac 0001
```

Basically, this migration was applied from the old repository, and now it's trying to reapply here, and it's redundant. So we want to tell the migration stuff to just ignore it and move on.

**Comment by mattrobenolt** [comment]
You may also need to do:

```
$ sentry django migrate --fake hipchat_ac 0002
```

If that second one fails too. I can't remember off the top of my head. But after this, a normal `sentry upgrade` should continue along just fine.

**Comment by JeanFred** [comment]
I ran both fake migrations and after that `sentry upgrade` worked − thanks!
