### ISSUE TITLE
[github] add support for github enterprise

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry-plugins#82]

**Comment by QingsongYao** [comment]
I have a PR to enable this. Hope it will be ready soon.

**Comment by agis-** [comment]
@QingsongYao Any updates on this?

**Comment by agis-** [comment]
@QingsongYao I believe the original issue is about a Github Enterprise Issue Plugin, not Github Enterprise SSO.

**Comment by johnwebbcole** [comment]
The issue plugin is what I would like also.  SSO isn't as high a priority as creating issue tickets.

**Comment by QingsongYao** [comment]
Both issues were stuck. https://github.com/getsentry/sentry/pull/5068 and https://github.com/getsentry/sentry-plugins/pull/208

**Comment by mandeepbal** [comment]
The api for the auth and issues should be the same between github.com and github enterprise. The API endpoint just needs to be configurable.

**Comment by bharathrajbk** [comment]
Guys,

I am looking forward to this feature as well. Can we please get the API endpoint configurable?

**Comment by ainformatico** [comment]
I can see two PRs closed created by @QingsongYao and no apparent reason why. Is there any reason why this feature is not implemented and PRs are being closed?

**Comment by bharathrajbk** [comment]
Yes. I have been asking for the same feature as well. 
@dcramer has commented on #https://github.com/getsentry/sentry-github/issues/27 that the feature will be added in GHE support sometime in Q2.

**Comment by bharathrajbk** [comment]
Sentry 9 was released. But this feature did not go in. Any reasons why this is not being looked at?

**Comment by dcramer** [comment]
@bharathrajbk GitLab was never part of Sentry 9. I'm going to close all related GitLab issues if we keep having to come onto the public tracker to post the same thing (that it is coming in Q2, which generally means will be released by Q3).

**Comment by rasmus** [comment]
Any progress on the GitHub Enterprise support, we are really looking forward to this

**Comment by dcramer** [comment]
GHE support will land for Sentry.io early adopters this month. 

I’m closing this ticket as we aren’t using GitHub to track progress on this. 

We’ll publish something on our blog and in app when the new integrations are live.

**Comment by rasmus** [comment]
😢 while you internally don't use it to track progress, we do

**Comment by dcramer** [comment]
@rasmus truthfully we’d forget to update the issue for 6 months anyways 😶

**Comment by agis** [comment]
@dcramer does this mean that it'll be in the next on-premise release?

**Comment by dcramer** [comment]
@agis it should be but we haven’t scheduled that release yet

**Comment by riseshia** [comment]
Is there any progress? It seems 9.0 doesn't ship this feature
