### ISSUE TITLE
Cannot create GitHub issues 

### ISSUE THREAD

**Issue by philippeowagner** [getsentry/sentry-plugins#90]
Getting this stack trace. Dit I forgot something to setup?! 

    NoReverseMatch: Reverse for 'socialauth_associate' with arguments '('github',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
    (3 additional frame(s) were not displayed)
    ...
      File "sentry/api/base.py", line 176, in dispatch
        response = handler(request, *args, **kwargs)
      File "sentry/plugins/endpoints.py", line 44, in get
        return self._handle(request, group, *args, **kwargs)
      File "sentry/plugins/endpoints.py", line 41, in _handle
        return self.view(request, group, *args, **kwargs)
      File "sentry/plugins/bases/issue2.py", line 208, in view_create
        auth_errors = self.check_config_and_auth(request, group)
      File "sentry/plugins/bases/issue2.py", line 347, in check_config_and_auth
        'auth_url': reverse('socialauth_associate', args=[self.auth_provider])

**Comment by mattrobenolt** [comment]
What version of sentry do you have? You must make sure you have the same version of sentry to go with sentry-plugins. 8.10 requires 8.10, etc.

**Comment by philippeowagner** [comment]
@mattrobenolt , we use

    sentry==8.10.0
    sentry-auth-github==0.1.0
    sentry-plugins==8.10.0
    django-social-auth==0.7.28

SSO with Github is set up and works as expected.

**Comment by mattrobenolt** [comment]
Oh, it's probably due to having `django-social-auth` installed. Uninstall that. We vendor our own version of social auth because reasons. https://github.com/getsentry/sentry/tree/master/src/social_auth

**Comment by mattrobenolt** [comment]
To be explicit, that error wouldn't happen if it were hitting oru social auth at least because of this rule: https://github.com/getsentry/sentry/blob/master/src/social_auth/urls.py#L13-L15

**Comment by philippeowagner** [comment]
After uninstalling as suggested I'm getting 

```
  File "/home/sentry/my-sentry/local/lib/python2.7/site-packages/sentry/plugins/bases/issue.py", line 15, in <module>
    from social_auth.models import UserSocialAuth
ImportError: No module named social_auth.models
```

**Comment by mattrobenolt** [comment]
I'd say something is wrong with your sentry install then. Or there was some behavior where that social auth was clobbering the one we provided ,and uninstalling it, also removed ours.

I'd try just uninstalling `sentry` and reinstalling it so it puts things where they should be.

**Comment by philippeowagner** [comment]
🎉 problem solved, thank you @mattrobenolt
