### ISSUE TITLE
[github] Automatic ticket creation

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry-plugins#94]

**Comment by alexrussell** [comment]
Assuming this request is to have Sentry automatically create issues on Gitlab rather than having to create them manually using the `GitLab → Create new issue` button, 👍  from me.

Also, I found this request in another [sentry-gitlab repo](https://github.com/ajcrowe/sentry-gitlab/issues/6) (possibly the original repo before it was merged into `getsentry/sentry-gitlab` and then `getsentry/sentry-plugins`, but I'm not sure), so just cross-referencing here.

**Comment by alexrussell** [comment]
Oh, I could've sworn this was GitLab not Github. Same deal for both I guess, and now that one repo manages them both, I imagine there's no point having two issues...?

**Comment by benvinegar** [comment]
We moved official Sentry plugins to this monorepo to simplify things.

**Comment by shahp00ja** [comment]
Is this feature now available for GitHub? 
" Sentry automatically create issues on Gitlab rather than having to create them manually using the GitHub → Create new issue button"

**Comment by alexrussell** [comment]
@shahp00ja sorry, this feature doesn't exist for Github or GitLab yet, my comment above was just clarifying the issue's meaning (as all we have to go on is the somewhat ambiguous title).

**Comment by alexrussell** [comment]
Though I imagine that once it's created for one of them, it's trivial to make it happen for the other.

**Comment by machadogj** [comment]
Will this be added?

**Comment by dt** [comment]
Has anyone looked at or tried hacking this functionality together with the existing webhooks support? I was about to try that, but just curious if someone else already has it working.

**Comment by jpike88** [comment]
+ 1

**Comment by mikkelam** [comment]
would also love this

**Comment by chrischris292** [comment]
this would be great

**Comment by tschottdorf** [comment]
Have also wanted this for https://github.com/cockroachdb/cockroach/issues

**Comment by pjatx** [comment]
I was able to achieve this using Zapier Webhooks -> GitHub. Works great!

**Comment by tschottdorf** [comment]
@pjatx interesting, what did you set up?  I thought the zapier->github section does the opposite, namely push information from Github to other platforms (and they don't appear to offer a specific sentry integration).

**Comment by pjatx** [comment]
@tschottdorf 

So Zapier has a fairly new `Webhooks` app which is just for consuming any kind of webhook and then you can send it to a number of Zapier apps including GitHub. 

![image](https://user-images.githubusercontent.com/5004634/45890481-b1bdad80-bd88-11e8-8e33-314eac3457e3.png)

During setup, they'll give you a webhook endpoint which you can take an then throw into sentry:
![image](https://user-images.githubusercontent.com/5004634/45890559-e3367900-bd88-11e8-8764-37f391416371.png)

![image](https://user-images.githubusercontent.com/5004634/45891654-bc2d7680-bd8b-11e8-9020-493c857d63ae.png)

Then you can select the GitHub app as the destination and the `Create Issue` as the type. Then you can map the fields from the webhook to various fields in the issue.

**Comment by tschottdorf** [comment]
Wonderful, thanks so much @pjatx!

**Comment by pjatx** [comment]
No problem! Glad I could be helpful!
