### ISSUE TITLE
[jira] support changing JIRA project when creating issues

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry-plugins#95]

**Comment by asherf** [comment]
👍 
we are having the same issue!

**Comment by voylinux** [comment]
We are facing this problem. I will try to give some context.
We have a self hosted Jira and self josted Sentry.

When configuring the integration, you are asked to select only one project in Jira with each project in Sentry.
Then, when creating an issue in Jira from a Sentry issue, the Jira projects selector is shown but inactive.
Is there a way to have a default Jira project but select the project when creating the issue?
